homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret hass_latitude
  longitude: !secret hass_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret hass_elevation
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Budapest

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  # Uncomment this to add a password (recommended!)
  # api_password: PASSWORD
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

influxdb:
  host: !secret influxdb_host

sensor:
  - platform: yr

  - platform: command_line
    name: "Server Rack"
    command: "python3 /vagrant/ediplug-py/src/ediplug/smartplug.py -H 192.168.1.80 -l admin -p 1234 -w | cut -d ' ' -f 1"
    unit_of_measurement: 'W'

  - platform: command_line
    name: "Air Conditioning"
    command: "python3 /vagrant/ediplug-py/src/ediplug/smartplug.py -H 192.168.1.83 -l admin -p 1234 -w | cut -d ' ' -f 1"
    unit_of_measurement: 'W'

  - platform: statistics
    entity_id: sensor.air_conditioning
    name: "Air Conditioning"

  - platform: statistics
    entity_id: sensor.server_rack
    name: "Server Rack"


# Text to speech
tts:
  platform: google

group: !include groups.yaml

mqtt:
  broker: !secret mqtt_host
  port: !secret mqtt_port
  client_id: home-assistant-1
  keepalive: 60
  username: !secret mqtt_username
  password: !secret mqtt_password
  protocol: 3.1

device_tracker:
  - platform: owntracks


automation:
  - alias: "Turn lights off when leaving"
    trigger:
      platform: state
      entity_id: device_tracker.phil_samsung_galaxy_s7
      state: 'not_home'
    action:
      service: homeassistant.turn_off
      entity_id: group.all_lights

  - alias: "Turn lights on when arriving"
    trigger:
      platform: state
      entity_id: device_tracker.phil_samsung_galaxy_s7
      state: 'home'
    action:
      service: homeassistant.turn_on
      entity_id: group.all_lights
