homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret hass_latitude
  longitude: !secret hass_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret hass_elevation
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Budapest


  customize:
    sensor.router_eth0_rx:
      hidden: true
    sensor.router_eth1_rx:
      hidden: true
    sensor.router_eth0_tx:
      hidden: true
    sensor.router_eth1_tx:
      hidden: true
    sensor.nas_lagg0_rx:
      hidden: true
    sensor.nas_lagg0_tx:
      hidden: true


# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  # Uncomment this to add a password (recommended!)
  # api_password: PASSWORD
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

influxdb:
  host: !secret influxdb_host

light:
  platform: hue
  host: Philips-Hue

sensor:
  - platform: yr
    monitored_conditions:
      - temperature
      - windSpeed
      - humidity

  - platform: command_line
    name: "Bedroom ambient temperature"
    command: !secret bedroom_ambient_temperature_command
    unit_of_measurement: '°C'
    scan_interval: 30

  - platform: command_line
    name: "Air Conditioning"
    command: "python3 /vagrant/ediplug-py/src/ediplug/smartplug.py -H 192.168.1.83 -l admin -p 12345678 -w | cut -d ' ' -f 1"
    unit_of_measurement: 'W'

  - platform: statistics
    entity_id: sensor.air_conditioning
    name: "Air Conditioning"

  - platform: statistics
    entity_id: sensor.server_rack
    name: "Server Rack"

  - platform: mqtt
    state_topic: "owntracks/phil/Samsung Galaxy s7"
    name: "Galaxy S7 Battery level"
    unit_of_measurement: "%"
    value_template: "{{ value_json.batt }}"

  - platform: mqtt
    state_topic: "tasker/phil/Sleep"
    name: "phil's sleep state"
    qos: 2

  - platform: snmp
    host: !secret router_host
    name: "router eth0 RX"
    baseoid: "1.3.6.1.2.1.31.1.1.1.6.2"
    version: "2c"
    community: !secret router_snmp_community

  - platform: snmp
    host: !secret router_host
    name: "router eth1 RX"
    baseoid: "1.3.6.1.2.1.31.1.1.1.6.3"
    version: "2c"
    community: !secret router_snmp_community

  - platform: snmp
    host: !secret router_host
    name: "router eth0 TX"
    baseoid: "1.3.6.1.2.1.31.1.1.1.10.2"
    version: "2c"
    community: !secret router_snmp_community

  - platform: snmp
    host: !secret router_host
    name: "router eth1 TX"
    baseoid: "1.3.6.1.2.1.31.1.1.1.10.3"
    version: "2c"
    community: !secret router_snmp_community

  - platform: snmp
    host: !secret nas_host
    name: "nas lagg0 RX"
    baseoid: "1.3.6.1.2.1.31.1.1.1.6.4"
    version: "2c"
    community: !secret nas_snmp_community

  - platform: snmp
    host: !secret nas_host
    name: "nas lagg0 TX"
    baseoid: "1.3.6.1.2.1.31.1.1.1.10.4"
    version: "2c"
    community: !secret nas_snmp_community


switch:
  - platform: broadlink
    host: !secret broadlink_living_room_host
    mac: !secret broadlink_living_room_mac
    type: rm_mini
    friendly_name: "Living room"
    switches:
      air_conditioning:
        friendly_name: "Air Conditioning @ Living Room"
        command_on: "JgB4AGQAASoQMhAQDxEQEBAQDxEOERAQEBEPMxARDxEPNBExEBEPNQ8REDIPMw80EjEQMxEyDzURMRARDxEQEQ80ETEPNQ8SDzMQEA8REBEPNA8zEDIREBAzDxEQEBARDzIQERAREBEPEQ8QEBAQERAyDzMRMxEyDwANBQ=="
        command_off: "JgB4AGIAAS0QMg4TEBEMFBAQDxENFBARDxMNNRAREBEQMw8SDjUMNw8SDTYONQ42DTYONQ02DjYNNg0TEBENEw81DTUONg0UDjUOEg4TDRMQNA02DjYNEw80DRQPERARDTYNEw4TDhQOEhARDRQPEQ0TDRQPMxA1DQANBQ=="
      roomba:
        friendly_name: "Roomba"
        command_on: "JgD8AGEgIV8gXyBfXCIhXyBfIAACoGIfIGAfYB9gXSIfYR5hHgACol8iHmIdYh1iXCIfYR5hHgACo2EgHmEfYR1iXCIeYh1iHQACq2AhH2EeYR9gXCMfYB9gHwAComAhH2AfYR9gXCIgYB9gHwACoWAiH2AfYB9gXCMfYB9hHgAComAhH2EeYR5hXCIgYCBfIAACoGEgIGAfYB9gXSIfYR5hHgACql8jHWIdYh1iXCMeYR5hHgACo18iHmEeYh1iXCIeYh1iHQACo18jHWIdYh5hXSIeYh1iHQACo18jHWIdYh1iXCIfYR5hHgACq18iHmEeYh1iXCIeYh1iHgANBQAAAAAAAAAAAAAAAA=="
        command_off: "JgCQAGAhHmIfYB9gH2BdIh5iXAACbGAhHmIeYR5hH2BdIh5iXAACZGAhHmIeYR5hH2BdIh5iXAACZGEhH2AfYB9gIF9eISBgXgACYl8iIGAfYB9gH2BfICBgXgACamEhH2AfYB9gH2BfICBgXgACYmEgIGAfYCBfIF9cIx9hXAACZGAhHmIeYR5hH2BdIh5iXAANBQAAAAAAAAAA"

  - platform: broadlink
    host: !secret broadlink_bedroom_host
    mac: !secret broadlink_bedroom_mac
    type: rm_mini
    friendly_name: "Bedroom"
    switches:
      air_conditioning:
        friendly_name: "Air Conditioning @ Bedroom"
        command_on: "JgB4AGUAASgPMxEPEQ8PEQ8REA8REA8REBERMhEPERAPMxAyETEQNBEQEDIRMhEyDxERMREQETMPMxAQEQ8SDxEQEDERMhERDzMREA8RERARMhAQEDIREBAzEQ8REBAQDzMRDxAQERARDxEPEQ8RDxEyEDERMhEyEAANBQ=="
        command_off: "JgB4AGUAASkQMhEPERAQDxAQEA8RDxAQERAPNA8REQ8RMg8REQ8RERAxETIPMxAyEQ8RMREQETMRMhEPEQ8RDxEQDzMQMhEQETEREBAQEBAPNBAQDzMQEBEyEQ8REBAPETIRDxEPERARDxEQEBAPEBEPERAQMg8zEQANBQ=="
      speakers_mute:
        friendly_name: "Speakers @ Bedroom"
        command_on: "JgBQAAABKZMTEhQRFBETEhMSFBETERQSEzYUERQ2FDcTNhQ2FDYUNhQ2FBEUERM3FBETEhMSFBETERQ3EzYUEhM2FDYUNhQ2FAAFRAABKUgUAA0FAAAAAAAAAAA=="
        command_off: "JgBQAAABKJQUEBMSExMTERMSFBEUERMSFDYTEhQ2EzcTNxM2EzgTNhM3ExITExMRExIUEhMRExIUERQ2EzcUNhM3EzcTNxM3EgAFRQABKUkTAA0FAAAAAAAAAAA=="


binary_sensor:
  - platform: ping
    host: !secret proxmox_address
    name: proxmox



# Text to speech
tts:
  platform: google

group: !include groups.yaml

mqtt:
  broker: !secret mqtt_host
  port: !secret mqtt_port
  client_id: home-assistant-1
  keepalive: 60
  username: !secret mqtt_username
  password: !secret mqtt_password
  protocol: 3.1

device_tracker:
  - platform: owntracks


automation:
  - alias: "Turn lights off when leaving"
    trigger:
      platform: state
      entity_id: device_tracker.phil_samsung_galaxy_s7
      to: 'not_home'
    action:
      service: homeassistant.turn_off
      entity_id: group.all_lights

  - alias: "Turn lights on when arriving"
    trigger:
      platform: state
      entity_id: device_tracker.phil_samsung_galaxy_s7
      to: 'home'
    action:
      service: homeassistant.turn_on
      entity_id: group.all_lights

  - alias: "Turn off air conditioning when leaving"
    trigger:
      platform: state
      entity_id: device_tracker.phil_samsung_galaxy_s7
      to: 'not_home'
    action:
      - service: homeassistant.turn_off
        entity_id: switch.air_conditioning__living_room
      - service: homeassistant.turn_off
        entity_id: switch.air_conditioning__bedroom

  - alias: "Daily vacuum cleaning"
    trigger:
      platform: time
      at: "13:30:00"
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: device_tracker.phil_samsung_galaxy_s7
          state: 'not_home'
    action:
      service: homeassistant.turn_on
      entity_id: switch.roomba

  - alias: "Turn vacuum cleaner off when arriving"
    trigger:
      platform: state
      entity_id: device_tracker.phil_samsung_galaxy_s7
      to: 'home'
    action:
      service: homeassistant.turn_off
      entity_id: switch.roomba
